services:
    dockerapp:
        image: dockerapp
        build:
            context: .
            dockerfile: ./Dockerfile
        environment:
            NODE_ENV: development
        ports:
            - 5173:5173
